
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'water_temp'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'water-temp'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["dbt/models"]
analysis-paths: ["dbt/analysis"]
test-paths: ["dbt/tests"]
seed-paths: ["dbt/data"]
macro-paths: ["dbt/macros"]
snapshot-paths: ["dbt/snapshots"]

target-path: "dbt/target"  # directory which will store compiled SQL files
log-path: "dbt/logs"
packages-install-path: "dbt/modules"
clean-targets:         # directories to be removed by `dbt clean`
    - "dbt/target"
    - "dbt/modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
    materialized: table
