# version: "3.7"
services:

  vscode-dev:
    image: project-watertemp-dev
    container_name: project-watertemp-vsc-dev
    depends_on:
      - db
    volumes:
      - .:/app
    env_file: .env
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  db:
    image: postgres:15.3
    container_name: project-watertemp-pg-db
    environment:
      - POSTGRES_PASSWORD=secret
      - PGDATA=/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/data/pgdata

  prod:
    image: project-watertemp
    container_name: project-watertemp-prod
    depends_on:
      - db
    env_file: .env
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

volumes:
  postgres-data:
