# version: "3.7"
services:

  vscode-dev:
    image: project-watertemp-dev
    container_name: project-watertemp-vsc-dev
    depends_on:
      - db
    volumes:
      - .:/app
    env_file: .env
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  db:
    image: postgres:latest
    container_name: project-watertemp-pg-db
    env_file: .env
    volumes:
      - ./data:/data
    ports:
      - 5432:5432
