# name of your pipeline
name: CI

# define some actions filters, when this build should be triggered
# here it is only triggered if a push is made on the master branch
on:
  push:
    branches:
      - main

env:
  global:
    DOCKER_BUILDKIT: 1

jobs:
# TODO: implement this in the future: check which files have changed in the last push
  # run build, but only if requirements.txt has changed
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      - name: Build base image
        run: make build
      - name: Build dev image
        run: make build-dev
      - name: Test app
        run: make dockerized-test
        run: heroku container:login
      - name: Push to Heroku container registry
        run: |
          docker tag project-watertemp registry.heroku.com/water-temp/web
          docker push registry.heroku.com/water-temp/web
          docker tag project-watertemp-dev registry.heroku.com/water-temp/web-dev
          docker push registry.heroku.com/water-temp/web-dev
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a water-temp web
