# name of your pipeline
name: CI

permissions:
  id-token: write
  contents: read

# define some actions filters, when this build should be triggered
# here it is only triggered if a push is made on the master branch
on:
  push:
    branches:
      - main
    paths:
      - '*Dockerfile'
      - 'tests/**'
      - 'src/**'
      - 'dbt/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'Makefile'
      - '.gitignore'
      - '.dockerignore'
      - 'dbt_project.yml'
      - '.github/**'


env:
  DOCKER_BUILDKIT: 1

jobs:
# TODO: implement this in the future: check which files have changed in the last push
  # run build, but only if requirements.txt has changed
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'water-temp-dash'
          workload_identity_provider: 'projects/576787685789/locations/global/workloadIdentityPools/github-pool/providers/github-provider'

      - name: Login to Artifact Registry
        run: |
          gcloud auth configure-docker europe-central2-docker.pkg.dev

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build base image
        run: make build

      - name: Build dev image
        run: make build-dev

      - name: Test app
        run: make dockerized-test

      - name: Push prod image to GCP container registry
        run: |
          docker tag project-watertemp europe-central2-docker.pkg.dev/water-temp-dash/water-temp-container-repo/project-watertemp
          docker push europe-central2-docker.pkg.dev/water-temp-dash/water-temp-container-repo/project-watertemp
